# Generated by Django 6.1 on 2026-08-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_sitevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='message_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='message_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='institution_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='institution_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='title_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='about_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='about_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='headline_en',
            field=models.CharField(default='IT Support | Systèmes & Réseaux | Full-Stack | IoT', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='headline_fr',
            field=models.CharField(default='IT Support | Systèmes & Réseaux | Full-Stack | IoT', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_en',
            field=models.CharField(default="N'Djamena, Tchad", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_fr',
            field=models.CharField(default="N'Djamena, Tchad", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name_en',
            field=models.CharField(default='Djimrosngue Ngarhodjim Justin', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name_fr',
            field=models.CharField(default='Djimrosngue Ngarhodjim Justin', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='short_bio_en',
            field=models.TextField(default="Passionné par les technologies, le développement logiciel, les systèmes informatiques et l'IoT.", null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='short_bio_fr',
            field=models.TextField(default="Passionné par les technologies, le développement logiciel, les systèmes informatiques et l'IoT.", null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_fr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_fr',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_fr',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
