# Generated by Django 6.1 on 2026-08-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_contactmessage_message_en_contactmessage_message_fr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('IT', 'IT Support'), ('NETWORK', 'Réseaux'), ('BACKEND', 'Backend'), ('MOBILE', 'Mobile'), ('WEB', 'Web'), ('IOT', 'IoT'), ('DATA', 'Data'), ('OTHER', 'OTher')], default='OTHER', max_length=20),
        ),
    ]
