# Generated by Django 6.1 on 2026-08-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('IT', 'IT Support'), ('NETWORK', 'Réseaux'), ('BACKEND', 'Backend'), ('MOBILE', 'Mobile'), ('WEB', 'Web'), ('IOT', 'IoT'), ('DATA', 'Data'), ('OTHER', 'Autre')], default='OTHER', max_length=20),
        ),
    ]
